/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UserRouteImport } from './routes/user'
import { Route as ReviewRouteImport } from './routes/review'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as RecommendationsRouteImport } from './routes/recommendations'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as LoginRouteImport } from './routes/login'
import { Route as JoinRouteImport } from './routes/join'
import { Route as CreateRouteImport } from './routes/create'
import { Route as IndexRouteImport } from './routes/index'
import { Route as GroupIndexRouteImport } from './routes/group.index'
import { Route as UserUserIdRouteImport } from './routes/user.$userId'
import { Route as GroupItemIdRouteImport } from './routes/group.$itemId'
import { Route as MediaGroupIdMediaIdRouteImport } from './routes/media.$groupId.$mediaId'
import { Route as EpisodeGroupIdMediaIdEpisodeIdRouteImport } from './routes/episode.$groupId.$mediaId.$episodeId'

const UserRoute = UserRouteImport.update({
  id: '/user',
  path: '/user',
  getParentRoute: () => rootRouteImport,
} as any)
const ReviewRoute = ReviewRouteImport.update({
  id: '/review',
  path: '/review',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const RecommendationsRoute = RecommendationsRouteImport.update({
  id: '/recommendations',
  path: '/recommendations',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const JoinRoute = JoinRouteImport.update({
  id: '/join',
  path: '/join',
  getParentRoute: () => rootRouteImport,
} as any)
const CreateRoute = CreateRouteImport.update({
  id: '/create',
  path: '/create',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const GroupIndexRoute = GroupIndexRouteImport.update({
  id: '/group/',
  path: '/group/',
  getParentRoute: () => rootRouteImport,
} as any)
const UserUserIdRoute = UserUserIdRouteImport.update({
  id: '/$userId',
  path: '/$userId',
  getParentRoute: () => UserRoute,
} as any)
const GroupItemIdRoute = GroupItemIdRouteImport.update({
  id: '/group/$itemId',
  path: '/group/$itemId',
  getParentRoute: () => rootRouteImport,
} as any)
const MediaGroupIdMediaIdRoute = MediaGroupIdMediaIdRouteImport.update({
  id: '/media/$groupId/$mediaId',
  path: '/media/$groupId/$mediaId',
  getParentRoute: () => rootRouteImport,
} as any)
const EpisodeGroupIdMediaIdEpisodeIdRoute =
  EpisodeGroupIdMediaIdEpisodeIdRouteImport.update({
    id: '/episode/$groupId/$mediaId/$episodeId',
    path: '/episode/$groupId/$mediaId/$episodeId',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/create': typeof CreateRoute
  '/join': typeof JoinRoute
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/recommendations': typeof RecommendationsRoute
  '/register': typeof RegisterRoute
  '/review': typeof ReviewRoute
  '/user': typeof UserRouteWithChildren
  '/group/$itemId': typeof GroupItemIdRoute
  '/user/$userId': typeof UserUserIdRoute
  '/group/': typeof GroupIndexRoute
  '/media/$groupId/$mediaId': typeof MediaGroupIdMediaIdRoute
  '/episode/$groupId/$mediaId/$episodeId': typeof EpisodeGroupIdMediaIdEpisodeIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/create': typeof CreateRoute
  '/join': typeof JoinRoute
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/recommendations': typeof RecommendationsRoute
  '/register': typeof RegisterRoute
  '/review': typeof ReviewRoute
  '/user': typeof UserRouteWithChildren
  '/group/$itemId': typeof GroupItemIdRoute
  '/user/$userId': typeof UserUserIdRoute
  '/group': typeof GroupIndexRoute
  '/media/$groupId/$mediaId': typeof MediaGroupIdMediaIdRoute
  '/episode/$groupId/$mediaId/$episodeId': typeof EpisodeGroupIdMediaIdEpisodeIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/create': typeof CreateRoute
  '/join': typeof JoinRoute
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/recommendations': typeof RecommendationsRoute
  '/register': typeof RegisterRoute
  '/review': typeof ReviewRoute
  '/user': typeof UserRouteWithChildren
  '/group/$itemId': typeof GroupItemIdRoute
  '/user/$userId': typeof UserUserIdRoute
  '/group/': typeof GroupIndexRoute
  '/media/$groupId/$mediaId': typeof MediaGroupIdMediaIdRoute
  '/episode/$groupId/$mediaId/$episodeId': typeof EpisodeGroupIdMediaIdEpisodeIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/create'
    | '/join'
    | '/login'
    | '/profile'
    | '/recommendations'
    | '/register'
    | '/review'
    | '/user'
    | '/group/$itemId'
    | '/user/$userId'
    | '/group/'
    | '/media/$groupId/$mediaId'
    | '/episode/$groupId/$mediaId/$episodeId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/create'
    | '/join'
    | '/login'
    | '/profile'
    | '/recommendations'
    | '/register'
    | '/review'
    | '/user'
    | '/group/$itemId'
    | '/user/$userId'
    | '/group'
    | '/media/$groupId/$mediaId'
    | '/episode/$groupId/$mediaId/$episodeId'
  id:
    | '__root__'
    | '/'
    | '/create'
    | '/join'
    | '/login'
    | '/profile'
    | '/recommendations'
    | '/register'
    | '/review'
    | '/user'
    | '/group/$itemId'
    | '/user/$userId'
    | '/group/'
    | '/media/$groupId/$mediaId'
    | '/episode/$groupId/$mediaId/$episodeId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CreateRoute: typeof CreateRoute
  JoinRoute: typeof JoinRoute
  LoginRoute: typeof LoginRoute
  ProfileRoute: typeof ProfileRoute
  RecommendationsRoute: typeof RecommendationsRoute
  RegisterRoute: typeof RegisterRoute
  ReviewRoute: typeof ReviewRoute
  UserRoute: typeof UserRouteWithChildren
  GroupItemIdRoute: typeof GroupItemIdRoute
  GroupIndexRoute: typeof GroupIndexRoute
  MediaGroupIdMediaIdRoute: typeof MediaGroupIdMediaIdRoute
  EpisodeGroupIdMediaIdEpisodeIdRoute: typeof EpisodeGroupIdMediaIdEpisodeIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/user': {
      id: '/user'
      path: '/user'
      fullPath: '/user'
      preLoaderRoute: typeof UserRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/review': {
      id: '/review'
      path: '/review'
      fullPath: '/review'
      preLoaderRoute: typeof ReviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recommendations': {
      id: '/recommendations'
      path: '/recommendations'
      fullPath: '/recommendations'
      preLoaderRoute: typeof RecommendationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/join': {
      id: '/join'
      path: '/join'
      fullPath: '/join'
      preLoaderRoute: typeof JoinRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/create': {
      id: '/create'
      path: '/create'
      fullPath: '/create'
      preLoaderRoute: typeof CreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/group/': {
      id: '/group/'
      path: '/group'
      fullPath: '/group/'
      preLoaderRoute: typeof GroupIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/user/$userId': {
      id: '/user/$userId'
      path: '/$userId'
      fullPath: '/user/$userId'
      preLoaderRoute: typeof UserUserIdRouteImport
      parentRoute: typeof UserRoute
    }
    '/group/$itemId': {
      id: '/group/$itemId'
      path: '/group/$itemId'
      fullPath: '/group/$itemId'
      preLoaderRoute: typeof GroupItemIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/media/$groupId/$mediaId': {
      id: '/media/$groupId/$mediaId'
      path: '/media/$groupId/$mediaId'
      fullPath: '/media/$groupId/$mediaId'
      preLoaderRoute: typeof MediaGroupIdMediaIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/episode/$groupId/$mediaId/$episodeId': {
      id: '/episode/$groupId/$mediaId/$episodeId'
      path: '/episode/$groupId/$mediaId/$episodeId'
      fullPath: '/episode/$groupId/$mediaId/$episodeId'
      preLoaderRoute: typeof EpisodeGroupIdMediaIdEpisodeIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface UserRouteChildren {
  UserUserIdRoute: typeof UserUserIdRoute
}

const UserRouteChildren: UserRouteChildren = {
  UserUserIdRoute: UserUserIdRoute,
}

const UserRouteWithChildren = UserRoute._addFileChildren(UserRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CreateRoute: CreateRoute,
  JoinRoute: JoinRoute,
  LoginRoute: LoginRoute,
  ProfileRoute: ProfileRoute,
  RecommendationsRoute: RecommendationsRoute,
  RegisterRoute: RegisterRoute,
  ReviewRoute: ReviewRoute,
  UserRoute: UserRouteWithChildren,
  GroupItemIdRoute: GroupItemIdRoute,
  GroupIndexRoute: GroupIndexRoute,
  MediaGroupIdMediaIdRoute: MediaGroupIdMediaIdRoute,
  EpisodeGroupIdMediaIdEpisodeIdRoute: EpisodeGroupIdMediaIdEpisodeIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
