/*
  # Add media_ai_overviews cache table

  1. New Tables
    - `media_ai_overviews`
      - `id` (uuid, primary key)
      - `tmdb_id` (integer) — TMDb ID of the movie/show
      - `media_type` (text) — 'movie' or 'show'
      - `title` (text) — title of the movie/show
      - `overview` (text) — AI-generated overview text
      - `generated_at` (timestamptz) — when the overview was generated
      - `updated_at` (timestamptz) — when last updated
      - UNIQUE constraint on (tmdb_id, media_type) to prevent duplicates

  2. Security
    - Enable RLS on `media_ai_overviews`
    - SELECT policy for authenticated users (anyone can read cached overviews)
    - INSERT/UPDATE policies for service role only (edge functions manage cache)

  3. Important Notes
    - This table caches AI-generated overviews for individual movies/shows
    - Prevents redundant AI calls for the same media item
    - The for-you-feed edge function checks this cache before calling AI
    - Overviews can be regenerated by deleting the cached row
*/

CREATE TABLE IF NOT EXISTS media_ai_overviews (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  tmdb_id integer NOT NULL,
  media_type text NOT NULL DEFAULT 'movie',
  title text NOT NULL DEFAULT '',
  overview text NOT NULL DEFAULT '',
  generated_at timestamptz DEFAULT now(),
  updated_at timestamptz DEFAULT now(),
  UNIQUE(tmdb_id, media_type)
);

ALTER TABLE media_ai_overviews ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Authenticated users can read media AI overviews"
  ON media_ai_overviews FOR SELECT
  TO authenticated
  USING (true);

CREATE POLICY "Service role can insert media AI overviews"
  ON media_ai_overviews FOR INSERT
  TO authenticated
  WITH CHECK (auth.uid() = '00000000-0000-0000-0000-000000000000');

CREATE POLICY "Service role can update media AI overviews"
  ON media_ai_overviews FOR UPDATE
  TO authenticated
  USING (auth.uid() = '00000000-0000-0000-0000-000000000000')
  WITH CHECK (auth.uid() = '00000000-0000-0000-0000-000000000000');

CREATE INDEX IF NOT EXISTS idx_media_ai_overviews_tmdb ON media_ai_overviews(tmdb_id, media_type);
